export {default as team1 } from "./team1.jpg";
export {default as team2 } from "./team2.jpg";
export {default as team3 } from "./team3.jpg";
export {default as team4 } from "./team4.jpg";
export {default as profile2} from "./profile-2.jpeg";
export {default as profile3} from "./profile-3.jpeg";
export {default as profile4} from "./profile-4.jpeg";
export {default as profile5} from "./profile-5.jpg";
export {default as profile6} from "./profile-6.png";
export {default as hero_image} from "./hero-image.png";
export {default as about_image} from "./about-image.jpg";
export {default as about1} from "./about1.jpg";
export {default as about2} from "./about2.jpg";
export {default as about3} from "./about3.jpg";
export {default as about4} from "./about4.jpg";
export {default as projc1} from "./projc1.jpg";
export {default as projc2} from "./projc2.jpg";
export {default as projc3 } from "./projc3.jpg" ;
export {default as projc4} from "./projc4.jpg";
export {default as projc5} from "./projc5.jpg";
export {default as projc6} from "./projc6.webp";
export {default as blog5} from "./blog5.avif";
export {default as blog6} from "./blog6.jpg";
export {default as blog7} from "./blog7.jpg";